#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace template.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_9B3C50_alert360db")]
	public partial class alert360dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdministrador(Administrador instance);
    partial void UpdateAdministrador(Administrador instance);
    partial void DeleteAdministrador(Administrador instance);
    partial void InsertAlerta(Alerta instance);
    partial void UpdateAlerta(Alerta instance);
    partial void DeleteAlerta(Alerta instance);
    partial void InsertReceptor(Receptor instance);
    partial void UpdateReceptor(Receptor instance);
    partial void DeleteReceptor(Receptor instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public alert360dbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_9B3C50_alert360dbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public alert360dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public alert360dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public alert360dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public alert360dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Administrador> Administradors
		{
			get
			{
				return this.GetTable<Administrador>();
			}
		}
		
		public System.Data.Linq.Table<Alerta> Alertas
		{
			get
			{
				return this.GetTable<Alerta>();
			}
		}
		
		public System.Data.Linq.Table<Receptor> Receptors
		{
			get
			{
				return this.GetTable<Receptor>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administrador")]
	public partial class Administrador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodAdministrador;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _IDAdministrador;
		
		private string _Contrasena;
		
		private System.Nullable<int> _Activo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodAdministradorChanging(int value);
    partial void OnCodAdministradorChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnIDAdministradorChanging(string value);
    partial void OnIDAdministradorChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnActivoChanging(System.Nullable<int> value);
    partial void OnActivoChanged();
    #endregion
		
		public Administrador()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodAdministrador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodAdministrador
		{
			get
			{
				return this._CodAdministrador;
			}
			set
			{
				if ((this._CodAdministrador != value))
				{
					this.OnCodAdministradorChanging(value);
					this.SendPropertyChanging();
					this._CodAdministrador = value;
					this.SendPropertyChanged("CodAdministrador");
					this.OnCodAdministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="NChar(10)")]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAdministrador", DbType="VarChar(20)")]
		public string IDAdministrador
		{
			get
			{
				return this._IDAdministrador;
			}
			set
			{
				if ((this._IDAdministrador != value))
				{
					this.OnIDAdministradorChanging(value);
					this.SendPropertyChanging();
					this._IDAdministrador = value;
					this.SendPropertyChanged("IDAdministrador");
					this.OnIDAdministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(50)")]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alerta")]
	public partial class Alerta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodAlerta;
		
		private int _CodUsuario;
		
		private System.Nullable<double> _Latitud;
		
		private System.Nullable<double> _Longitud;
		
		private string _Fecha;
		
		private System.Nullable<double> _HusoHorario;
		
		private System.Nullable<int> _Tipo;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodAlertaChanging(int value);
    partial void OnCodAlertaChanged();
    partial void OnCodUsuarioChanging(int value);
    partial void OnCodUsuarioChanged();
    partial void OnLatitudChanging(System.Nullable<double> value);
    partial void OnLatitudChanged();
    partial void OnLongitudChanging(System.Nullable<double> value);
    partial void OnLongitudChanged();
    partial void OnFechaChanging(string value);
    partial void OnFechaChanged();
    partial void OnHusoHorarioChanging(System.Nullable<double> value);
    partial void OnHusoHorarioChanged();
    partial void OnTipoChanging(System.Nullable<int> value);
    partial void OnTipoChanged();
    #endregion
		
		public Alerta()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodAlerta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodAlerta
		{
			get
			{
				return this._CodAlerta;
			}
			set
			{
				if ((this._CodAlerta != value))
				{
					this.OnCodAlertaChanging(value);
					this.SendPropertyChanging();
					this._CodAlerta = value;
					this.SendPropertyChanged("CodAlerta");
					this.OnCodAlertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodUsuarioChanging(value);
					this.SendPropertyChanging();
					this._CodUsuario = value;
					this.SendPropertyChanged("CodUsuario");
					this.OnCodUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitud", DbType="Float")]
		public System.Nullable<double> Latitud
		{
			get
			{
				return this._Latitud;
			}
			set
			{
				if ((this._Latitud != value))
				{
					this.OnLatitudChanging(value);
					this.SendPropertyChanging();
					this._Latitud = value;
					this.SendPropertyChanged("Latitud");
					this.OnLatitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitud", DbType="Float")]
		public System.Nullable<double> Longitud
		{
			get
			{
				return this._Longitud;
			}
			set
			{
				if ((this._Longitud != value))
				{
					this.OnLongitudChanging(value);
					this.SendPropertyChanging();
					this._Longitud = value;
					this.SendPropertyChanged("Longitud");
					this.OnLongitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="VarChar(50)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HusoHorario", DbType="Float")]
		public System.Nullable<double> HusoHorario
		{
			get
			{
				return this._HusoHorario;
			}
			set
			{
				if ((this._HusoHorario != value))
				{
					this.OnHusoHorarioChanging(value);
					this.SendPropertyChanging();
					this._HusoHorario = value;
					this.SendPropertyChanged("HusoHorario");
					this.OnHusoHorarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="Int")]
		public System.Nullable<int> Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Alerta", Storage="_Usuario", ThisKey="CodUsuario", OtherKey="CodUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Alertas.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Alertas.Add(this);
						this._CodUsuario = value.CodUsuario;
					}
					else
					{
						this._CodUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Receptor")]
	public partial class Receptor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodReceptor;
		
		private int _CodUsuario;
		
		private string _Nombre;
		
		private string _CorreoElectronico;
		
		private string _TelefonoUno;
		
		private string _TelefonoDos;
		
		private string _TelefonoTres;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodReceptorChanging(int value);
    partial void OnCodReceptorChanged();
    partial void OnCodUsuarioChanging(int value);
    partial void OnCodUsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCorreoElectronicoChanging(string value);
    partial void OnCorreoElectronicoChanged();
    partial void OnTelefonoUnoChanging(string value);
    partial void OnTelefonoUnoChanged();
    partial void OnTelefonoDosChanging(string value);
    partial void OnTelefonoDosChanged();
    partial void OnTelefonoTresChanging(string value);
    partial void OnTelefonoTresChanged();
    #endregion
		
		public Receptor()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodReceptor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodReceptor
		{
			get
			{
				return this._CodReceptor;
			}
			set
			{
				if ((this._CodReceptor != value))
				{
					this.OnCodReceptorChanging(value);
					this.SendPropertyChanging();
					this._CodReceptor = value;
					this.SendPropertyChanged("CodReceptor");
					this.OnCodReceptorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodUsuarioChanging(value);
					this.SendPropertyChanging();
					this._CodUsuario = value;
					this.SendPropertyChanged("CodUsuario");
					this.OnCodUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoElectronico", DbType="VarChar(80)")]
		public string CorreoElectronico
		{
			get
			{
				return this._CorreoElectronico;
			}
			set
			{
				if ((this._CorreoElectronico != value))
				{
					this.OnCorreoElectronicoChanging(value);
					this.SendPropertyChanging();
					this._CorreoElectronico = value;
					this.SendPropertyChanged("CorreoElectronico");
					this.OnCorreoElectronicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoUno", DbType="VarChar(10)")]
		public string TelefonoUno
		{
			get
			{
				return this._TelefonoUno;
			}
			set
			{
				if ((this._TelefonoUno != value))
				{
					this.OnTelefonoUnoChanging(value);
					this.SendPropertyChanging();
					this._TelefonoUno = value;
					this.SendPropertyChanged("TelefonoUno");
					this.OnTelefonoUnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoDos", DbType="VarChar(10)")]
		public string TelefonoDos
		{
			get
			{
				return this._TelefonoDos;
			}
			set
			{
				if ((this._TelefonoDos != value))
				{
					this.OnTelefonoDosChanging(value);
					this.SendPropertyChanging();
					this._TelefonoDos = value;
					this.SendPropertyChanged("TelefonoDos");
					this.OnTelefonoDosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoTres", DbType="VarChar(10)")]
		public string TelefonoTres
		{
			get
			{
				return this._TelefonoTres;
			}
			set
			{
				if ((this._TelefonoTres != value))
				{
					this.OnTelefonoTresChanging(value);
					this.SendPropertyChanging();
					this._TelefonoTres = value;
					this.SendPropertyChanged("TelefonoTres");
					this.OnTelefonoTresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Receptor", Storage="_Usuario", ThisKey="CodUsuario", OtherKey="CodUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Receptors.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Receptors.Add(this);
						this._CodUsuario = value.CodUsuario;
					}
					else
					{
						this._CodUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodUsuario;
		
		private string _Nombres;
		
		private string _Apellidos;
		
		private string _IDUsuario;
		
		private string _Contrasena;
		
		private System.Nullable<int> _Activo;
		
		private EntitySet<Alerta> _Alertas;
		
		private EntitySet<Receptor> _Receptors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodUsuarioChanging(int value);
    partial void OnCodUsuarioChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnIDUsuarioChanging(string value);
    partial void OnIDUsuarioChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnActivoChanging(System.Nullable<int> value);
    partial void OnActivoChanged();
    #endregion
		
		public Usuario()
		{
			this._Alertas = new EntitySet<Alerta>(new Action<Alerta>(this.attach_Alertas), new Action<Alerta>(this.detach_Alertas));
			this._Receptors = new EntitySet<Receptor>(new Action<Receptor>(this.attach_Receptors), new Action<Receptor>(this.detach_Receptors));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodUsuario
		{
			get
			{
				return this._CodUsuario;
			}
			set
			{
				if ((this._CodUsuario != value))
				{
					this.OnCodUsuarioChanging(value);
					this.SendPropertyChanging();
					this._CodUsuario = value;
					this.SendPropertyChanged("CodUsuario");
					this.OnCodUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(50)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(50)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDUsuario", DbType="VarChar(20)")]
		public string IDUsuario
		{
			get
			{
				return this._IDUsuario;
			}
			set
			{
				if ((this._IDUsuario != value))
				{
					this.OnIDUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IDUsuario = value;
					this.SendPropertyChanged("IDUsuario");
					this.OnIDUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(50)")]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Int")]
		public System.Nullable<int> Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this.OnActivoChanging(value);
					this.SendPropertyChanging();
					this._Activo = value;
					this.SendPropertyChanged("Activo");
					this.OnActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Alerta", Storage="_Alertas", ThisKey="CodUsuario", OtherKey="CodUsuario")]
		public EntitySet<Alerta> Alertas
		{
			get
			{
				return this._Alertas;
			}
			set
			{
				this._Alertas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Receptor", Storage="_Receptors", ThisKey="CodUsuario", OtherKey="CodUsuario")]
		public EntitySet<Receptor> Receptors
		{
			get
			{
				return this._Receptors;
			}
			set
			{
				this._Receptors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alertas(Alerta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Alertas(Alerta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Receptors(Receptor entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Receptors(Receptor entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
}
#pragma warning restore 1591
